from tkinter import*
window=Tk()
window.title("Tkinter New")
window.geometry("300x400")
greeting=Label(text="Welcome to Tkinter Window!", fg="white", bg="black")
button=Button(text="Click Me!", bg="black", fg="white")
entry=Entry(fg="yellow", bg="blue", width="50")
greeting.pack()
button.pack()
entry.pack()
frame=Frame(master=window, relief=SUNKEN, borderwidth=5)
frame.pack()
label=Label(master=frame, text="mylabel")
label.pack()
textbox=Text(fg="green", bg="yellow")
textbox.pack()
window.mainloop()