lst=["Red", "Orange", "Yellow", "Green", "Blue", "Purple"]
num = lst.index("Orange")
print(num)
print(lst)
print(lst[-1])
print(lst[0])
lst.append("Pink")
print(lst)
lst.remove("Green")
print(lst)
lst.sort()
print(lst)
lst.pop(2)
print(lst)
lst.reverse()
print("reversed list",lst)
print("multiplication on list",lst*4)
lst1=lst[1:]
print(lst1)
lst.clear()
print(lst)